---
extends: default

ignore: |
  charts/**/charts/
  charts/**/Chart.lock
  charts/**/templates/**
  .git/

rules:
  document-start: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  comments-indentation: disable
