---
extends: default

ignore: |
  charts/**/charts/
  charts/**/Chart.lock
  charts/**/templates/**
  .git/
  **/*.tpl

rules:
  document-start: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  braces: disable
  brackets: disable
  truthy:
    allowed-values: [ 'true', 'false', 'yes', 'no', 'on', 'off' ]
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
