apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: 'https://github.com/sm-moshi/helm-charts'
    path: charts/argus
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        ingress:
          main:
            enabled: false
        config:
          data:
            settings:
              web:
                listen_addr: 0.0.0.0
                listen_port: 8080
            service: {}
        secret:
          existingSecret: argus-discord-webhook
          envFrom: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
