apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cyberchef
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: 'https://github.com/sm-moshi/helm-charts'
    path: charts/cyberchef
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        ingress:
          main:
            enabled: false
            hosts:
              - host: cyberchef.example.com
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: http

  destination:
    server: https://kubernetes.default.svc
    namespace: cyberchef

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
